name: firebase_offline
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.11
  cloud_functions: ^5.6.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.1
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_sign_in: ^7.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
